### ISSUE TITLE
Dumb question - is it possible to disable lightning?

### ISSUE THREAD

**Issue by johnpc** [SatSale/SatSale#177]
I do not have enough liquidity to accept donations via lightning. I would like the default page to be the on-chain donation. If possible I would like to remove the lightning option entirely. Is this possible though some environment variable?

**Comment by nickfarrow** [comment]
Yes it is possible!

Just change the first line in `config.toml`:
```
payment_methods = ["bitcoind"]
```
Or `xpub` instead of `bitcoind` or whatver you are using.

**Comment by johnpc** [comment]
That's promising! However, my question is about to get dumber. I do not have a config.toml at all, I only have docker-compose file. 

```
services:
  web:
    image: satsale/satsale:0.1.13@sha256:98380ad6c5166d83e627c4d1f4efdbcfd5b9217096f7fb26b287fda89eebccbb
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/lnd:ro
    environment:
      DATA_DIR: /data
      LND_DATA_DIR: $APP_LIGHTNING_NODE_DATA_DIR
      LND_HOST: $APP_LIGHTNING_NODE_IP
      LND_GRPC_PORT: $APP_LIGHTNING_NODE_GRPC_PORT
      MACAROON_FILE: /lnd/data/chain/bitcoin/${APP_BITCOIN_NETWORK}/invoice.macaroon
      TLS_FILE: /lnd/tls.cert
      APP_PASSWORD: $APP_PASSWORD
    container_name: satsale_web_1
```

Is it possible to set these payment methods as an env var? Even when I exec into the docker host, Nothing turns up from `find / -name "*.toml"`. So somehow I'm getting by without any config file at all?
